### ISSUE TITLE
Fix demos for unicode URIs

### ISSUE THREAD

**Issue by jegger** [tavendo/AutobahnPython#266]
I claim that the example [votegame] (https://github.com/tavendo/AutobahnPython/blob/master/examples/twisted/wamp/wamplet/votegame/votegame/backend.py) isn't working with the current master.

I'm new to Autobahn and don't know if I missed something or what ever. Setting the uri in the decorator to unicode by u"com.votegame.*" fixes it (obviously), but should it be like that?

Ou yea and here's the error I get (running with python2.7): 
Traceback (most recent call last):
  File "AutobahnPython/examples/twisted/wamp/wamplet/votegame/votegame/backend.py", line 35, in <module>
    class VoteGameBackend(ApplicationSession):
  File "AutobahnPython/examples/twisted/wamp/wamplet/votegame/votegame/backend.py", line 71, in VoteGameBackend
    @wamp.register("com.votegame.get_votes")
  File "/Users/jg/code/brainwrite-autobahn/venv/lib/python2.7/site-packages/autobahn-0.9.0-py2.7.egg/autobahn/wamp/__init__.py", line 32, in decorate
    f._wampuris.append(Pattern(uri, Pattern.URI_TARGET_ENDPOINT))
  File "/Users/jg/code/brainwrite-autobahn/venv/lib/python2.7/site-packages/autobahn-0.9.0-py2.7.egg/autobahn/wamp/uri.py", line 78, in __init__
    assert(type(uri) == six.text_type)
AssertionError

**Comment by oberstet** [comment]
has been cleaned up
