### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'publish'" in crochet demo

### ISSUE THREAD

**Issue by sametmax** [tavendo/AutobahnPython#315]
Crochet demo (https://github.com/tavendo/AutobahnPython/blob/master/examples/twisted/wamp/app/crochet/example1/) is broken. You can easily fix the first error by removing the obsolete stand_alone parameter, but the second error kinda baffles me : 

```
INFO:werkzeug: * Running on http://127.0.0.1:8000/
   INFO:twisted:Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory instance at 0x7f968917ab48>
   INFO:twisted:Stopping factory <autobahn.twisted.websocket.WampWebSocketClientFactory instance at 0x7f968917ab48>
   ERROR:__main__:Exception on / [GET]
   Traceback (most recent call last):
     File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
       response = self.full_dispatch_request()
     File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
       rv = self.handle_user_exception(e)
     File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
       reraise(exc_type, exc_value, tb)
     File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
       rv = self.dispatch_request()
     File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
       return self.view_functions[rule.endpoint](**req.view_args)
     File "server.py", line 49, in index
       publish('com.example.on_visit', app._visits, msg = "hello from flask")
     File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 461, in wrapper
       return eventual_result.wait(timeout)
     File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 231, in wait
       result.raiseException()
     File "<string>", line 2, in raiseException
   AttributeError: 'NoneType' object has no attribute 'publish'
```

Since publish() is a function, I'm guessing it is a deep internal problem and crochet is propably making some dark magic with the module import to which it expects the publish function to be attached.

Any idea ?

**Comment by oberstet** [comment]
with some smallish adjusts, this works for me now .. see screenshot here https://github.com/tavendo/AutobahnPython/tree/master/examples/twisted/wamp/app/crochet/example1
