### ISSUE TITLE
error on python 3.4 (using asyncio)

### ISSUE THREAD

**Issue by allspace** [tavendo/AutobahnPython#405]
Python 3.4 on windows
Run the sample python wamp code (asyncio), got the following errors:

Traceback (most recent call last):
  File "port.py", line 1, in <module>
    from autobahn.asyncio.wamp import ApplicationSession
  File "C:\Python34\lib\site-packages\autobahn\asyncio\wamp.py", line 29, in <mo
dule>
    from autobahn.wamp import protocol
  File "C:\Python34\lib\site-packages\autobahn\wamp\protocol.py", line 53, in <m
odule>
    import txaio
  File "C:\Python34\lib\site-packages\txaio\__init__.py", line 99, in <module>
    from txaio.tx import *  # noqa
  File "C:\Python34\lib\site-packages\txaio\tx.py", line 28, in <module>
    from twisted.internet.defer import maybeDeferred, Deferred, DeferredList
  File "C:\Python34\lib\site-packages\twisted\internet\defer.py", line 29, in <m
odule>
    from twisted.python import lockfile, failure
  File "C:\Python34\lib\site-packages\twisted\python\lockfile.py", line 52, in <
module>
    _open = file
NameError: name 'file' is not defined

**Comment by allspace** [comment]
no matter asyncio or twisted, both get the same error.

**Comment by oberstet** [comment]
Twisted does not yet support py 3

**Comment by allspace** [comment]
Here is my imports. I expect it can use the asyncio in python 3.4 stdlib. Why does it still involve Twisted?

from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.wamp import ApplicationRunner

**Comment by oberstet** [comment]
`pip install autobahn[asyncio]` in a fresh Py3

**Comment by allspace** [comment]
Thanks. I finally figured out the problem. There is a Twisted installation in my python3 folder.

Once I uninstalled the Twisted, the asyncio method works well now.

**Comment by tusharmath** [comment]
The documentation says —
>>compatible with Python 2.6, 2.7, 3.3 and 3.4
But it doesn't work with python3?
