### ISSUE TITLE
Error with python2

### ISSUE THREAD

**Issue by amalfra** [tavendo/AutobahnPython#434]
Getting this error when using with python2.

Traceback (most recent call last):
  File "worker.py", line 10, in <module>
    from autobahn.asyncio.websocket import WebSocketClientProtocol, \
  File "/tmp/lib/python2.7/site-packages/autobahn/asyncio/websocket.py", line 29, in <module>
    from autobahn.wamp import websocket
  File "/tmp/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 31, in <module>
    from autobahn.websocket import protocol
  File "/tmp/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 56, in <module>
    import txaio
  File "/tmp/lib/python2.7/site-packages/txaio/__init__.py", line 103, in <module>
    from txaio.aio import *  # noqa
  File "/tmp/lib/python2.7/site-packages/txaio/aio.py", line 37, in <module>
    import asyncio
  File "/tmp/lib/python2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/tmp/lib/python2.7/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax

Any idea what's wrong?

**Comment by goeddea** [comment]
No idea. Could you give us some more information about how you're using Autobahn and your environment?

**Comment by amalfra** [comment]
from autobahn.asyncio.websocket import WebSocketClientProtocol, WebSocketClientFactory

This import line throws me the error. I am working on a python virtual env.

**Comment by meejah** [comment]
Looks like you (now) get either an ``ImportError`` *or* a ``SyntaxError`` when trying to import asyncio on Python 2.7 (with trollius installed) and both txaio and Autobahn only catch ``ImportError`` when testing for asyncio (and using trollius as the backup).

Can you use Python 3 for now? This will take (minor) fixes to both txaio and autobahn...

**Comment by amalfra** [comment]
Okay.

**Comment by oberstet** [comment]
the problem comes from installing the asyncio package, not the trollius package (which you should use). pls see the comments here: https://github.com/tavendo/txaio/issues/5
