### ISSUE TITLE
Make mock happy

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#436]
currently, setup.py requires mock==1.0.1 for dev.

and it seems to fail when mock is upgraded:

```console
(cpy2710_1)oberstet@corei7ub1310:~/scm/tavendo/autobahn/AutobahnPython$ pip install -U mock
Collecting mock
  Using cached mock-1.3.0-py2.py3-none-any.whl
Requirement already up-to-date: funcsigs in /home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages (from mock)
Requirement already up-to-date: pbr>=0.11 in /home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages (from mock)
Requirement already up-to-date: six>=1.7 in /home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages (from mock)
Installing collected packages: mock
  Found existing installation: mock 1.0.1
    Uninstalling mock-1.0.1:
      Successfully uninstalled mock-1.0.1
Successfully installed mock-1.3.0
(cpy2710_1)oberstet@corei7ub1310:~/scm/tavendo/autobahn/AutobahnPython$ USE_TWISTED=1 trial autobahn.twisted.test.test_application_runner
autobahn.twisted.test.test_application_runner
  TestApplicationRunner
    test_runner_default ...                                              [FAIL]
    test_runner_no_run ...                                               [FAIL]
    test_runner_no_run_happypath ...                                     [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/oberstet/scm/tavendo/autobahn/AutobahnPython/autobahn/twisted/test/test_application_runner.py", line 57, in test_runner_default
    self.assertEqual(len(run_calls), 1)
  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 437, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/home/oberstet/tmp/cpy2710/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/oberstet/tmp/cpy2710/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 3 != 1

autobahn.twisted.test.test_application_runner.TestApplicationRunner.test_runner_default
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/oberstet/scm/tavendo/autobahn/AutobahnPython/autobahn/twisted/test/test_application_runner.py", line 78, in test_runner_no_run
    self.assertEqual(len(run_calls), 0)
  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 437, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/home/oberstet/tmp/cpy2710/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/oberstet/tmp/cpy2710/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 0

autobahn.twisted.test.test_application_runner.TestApplicationRunner.test_runner_no_run
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/oberstet/scm/tavendo/autobahn/AutobahnPython/autobahn/twisted/test/test_application_runner.py", line 99, in test_runner_no_run_happypath
    self.assertEqual(len(run_calls), 0)
  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 437, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/home/oberstet/tmp/cpy2710/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/oberstet/tmp/cpy2710/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 0

autobahn.twisted.test.test_application_runner.TestApplicationRunner.test_runner_no_run_happypath
-------------------------------------------------------------------------------
Ran 3 tests in 0.020s

FAILED (failures=3)
(cpy2710_1)oberstet@corei7ub1310:~/scm/tavendo/autobahn/AutobahnPython$ 
```

**Comment by oberstet** [comment]
@meejah could you have a look pls?
