### ISSUE TITLE
Running "all examples" has an issue

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#437]
when doing `cd examples; make examples`, it bails out here:

```console
--------------------------------------------------------------------------------
Running example: ./asyncio/wamp/overview
--------------------------------------------------------------------------------

  starting backend
 backend: Upon execvpe ./venv-py3/bin/python ['./venv-py3/bin/python', './asyncio/wamp/overview/backend.py'] in environment id 47892507691280
 backend: :Traceback (most recent call last):
 backend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/internet/process.py", line 424, in _fork
 backend:     environment)
 backend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/internet/process.py", line 502, in _execChild
 backend:     os.execvpe(executable, args, environment)
 backend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/os.py", line 355, in execvpe
 backend:     _execvpe(file, args, env)
 backend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/os.py", line 370, in _execvpe
 backend:     func(file, *argrest)
 backend: OSError: [Errno 2] No such file or directory
  starting frontend
frontend: Upon execvpe ./venv-py3/bin/python ['./venv-py3/bin/python', './asyncio/wamp/overview/frontend.py'] in environment id 47892507690720
frontend: :Traceback (most recent call last):
frontend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/internet/process.py", line 424, in _fork
frontend:     environment)
frontend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/internet/process.py", line 502, in _execChild
frontend:     os.execvpe(executable, args, environment)
frontend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/os.py", line 355, in execvpe
frontend:     _execvpe(file, args, env)
frontend:   File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/os.py", line 370, in _execvpe
frontend:     func(file, *argrest)
frontend: OSError: [Errno 2] No such file or directory
FAILED: Process exited with code "1".
FAILED: Process exited with code "1".
Killing crossbar
```

**Comment by oberstet** [comment]
@meejah ?

**Comment by meejah** [comment]
With python2 it seems to work; with python3 I don't get any output due to some weird bytes/str issue but I don't get the same error as you...

From your error above, it seems like it can't find the python executable for some reason...

Does it at least work for you with Python2?

**Comment by meejah** [comment]
With a minor fix (`data.decode('utf8')` for out/errReceived) for `run-all-examples.py` for python3 then all the examples run through (master autobahn + crossbar).

**Comment by oberstet** [comment]
@meejah the log above is from running under Python 2 (virtualenv)

**Comment by oberstet** [comment]
another box:

```console
--------------------------------------------------------------------------------
Running example: ./asyncio/wamp/overview
--------------------------------------------------------------------------------

  starting backend
 backend: Upon execvpe ./venv-py3/bin/python ['./venv-py3/bin/python', './asyncio/wamp/overview/backend.py'] in environment id 47665757702976
 backend: :Traceback (most recent call last):
 backend:   File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/process.py", line 424, in _fork
 backend:     environment)
 backend:   File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/process.py", line 502, in _execChild
 backend:     os.execvpe(executable, args, environment)
 backend:   File "/home/oberstet/python279_1/lib/python2.7/os.py", line 355, in execvpe
 backend:     _execvpe(file, args, env)
 backend:   File "/home/oberstet/python279_1/lib/python2.7/os.py", line 370, in _execvpe
 backend:     func(file, *argrest)
 backend: OSError: [Errno 2] No such file or directory
  starting frontend
frontend: Upon execvpe ./venv-py3/bin/python ['./venv-py3/bin/python', './asyncio/wamp/overview/frontend.py'] in environment id 47665757702416
frontend: :Traceback (most recent call last):
frontend:   File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/process.py", line 424, in _fork
frontend:     environment)
frontend:   File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/process.py", line 502, in _execChild
frontend:     os.execvpe(executable, args, environment)
frontend:   File "/home/oberstet/python279_1/lib/python2.7/os.py", line 355, in execvpe
frontend:     _execvpe(file, args, env)
frontend:   File "/home/oberstet/python279_1/lib/python2.7/os.py", line 370, in _execvpe
frontend:     func(file, *argrest)
frontend: OSError: [Errno 2] No such file or directory
FAILED: Process exited with code "1".
FAILED: Process exited with code "1".
Killing crossbar
(python279_1)oberstet@thinkpad-t430s:~/scm/autobahn/AutobahnPython/examples$ python
Python 2.7.9 (default, Jan 18 2015, 21:40:29) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
(python279_1)oberstet@thinkpad-t430s:~/scm/autobahn/AutobahnPython/examples$ which python
/home/oberstet/python279_1/bin/python
(python279_1)oberstet@thinkpad-t430s:~/scm/autobahn/AutobahnPython/examples$ ls -la `which python`
-rwxrwxr-x 1 oberstet oberstet 8309950 Jan 18  2015 /home/oberstet/python279_1/bin/python
```

**Comment by meejah** [comment]
Okay, spotted a hard-coded path for Python3; I will fix.
