### ISSUE TITLE
exceptions.AttributeError: 'WsProtocol' object has no attribute 'is_closed'

### ISSUE THREAD

**Issue by tardyp** [tavendo/AutobahnPython#462]
FYI, we have a user reporting this backtrace:
http://trac.buildbot.net/ticket/3332

2015-08-10 08:52:18+0200 [HTTPChannel,5,192.168.11.56] Unhandled Error
	Traceback (most recent call last):
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in doRead
	    return self._dataReceived(data)
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 221, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 102, in dataReceived
	    self._dataReceived(data)
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1313, in _dataReceived
	    self.consumeData()
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1328, in consumeData
	    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1480, in processData
	    return self.processDataHybi()
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1791, in processDataHybi
	    fr = self.onFrameEnd()
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1889, in onFrameEnd
	    self.processControlFrame()
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1945, in processControlFrame
	    if self.onCloseFrame(code, reasonRaw):
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 869, in onCloseFrame
	    self.dropConnection(abort=False)
	  File "/home/benoit/buildbot/venv-beta/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 979, in dropConnection
	    txaio.resolve(self.is_closed, self)
	exceptions.AttributeError: 'WsProtocol' object has no attribute 'is_closed'
	
2015-08-10 08:52:18+0200 [<buildbot.www.ws.WsProtocol object at 0x7fc36859fb10>] connection lost

**Comment by meejah** [comment]
Is ``WsProtocol`` calling its ``super().__init__``?

**Comment by tardyp** [comment]
indeed, it is not. I did not realize WsProtocol was my code..

https://github.com/buildbot/buildbot/pull/1826

sorry for the noise
