### ISSUE TITLE
Import from private Twisted module breaks Autobahn on Windows

### ISSUE THREAD

**Issue by egwhoi** [tavendo/AutobahnPython#487]
When running on Windows with Twisted 15.4.0, the changes made in c517e9f generate an exception, since importing ```PipeAddress``` from ```twisted.internet._posixstdio``` calls ```detectLinuxBrokenPipeBehavior```, which only works on Posix systems.

Removing the changes from this commit fixes the problem, and seems to only make a cosmetic change.  Arguably, importing from a private module is fraught with peril, and probably shouldn't be done.

Here is an example stack trace showing the problem:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\crossbar-script.py", line 9, in <module>
    load_entry_point('crossbar==0.10.4', 'console_scripts', 'crossbar')()
  File "C:\Python27\lib\site-packages\crossbar\controller\cli.py", line 665, in run
    options.func(options)
  File "C:\Python27\lib\site-packages\crossbar\controller\cli.py", line 402, in run_command_start
    from crossbar.controller.node import Node
  File "C:\Python27\lib\site-packages\crossbar\controller\node.py", line 51, in <module>
    from crossbar.controller.process import NodeControllerSession
  File "C:\Python27\lib\site-packages\crossbar\controller\process.py", line 52, in <module>
    from autobahn.twisted.util import sleep
  File "C:\Python27\lib\site-packages\autobahn\twisted\util.py", line 31, in <module>
    from twisted.internet._posixstdio import PipeAddress
  File "C:\Python27\lib\site-packages\twisted\internet\_posixstdio.py", line 16, in <module>
    from twisted.internet import process, error, interfaces
  File "C:\Python27\lib\site-packages\twisted\internet\process.py", line 119, in <module>
    brokenLinuxPipeBehavior = detectLinuxBrokenPipeBehavior()
  File "C:\Python27\lib\site-packages\twisted\internet\process.py", line 107, in detectLinuxBrokenPipeBehavior
    reads, writes, exes = select.select([w], [], [], 0)
select.error: (10038, 'An operation was attempted on something that is not a socket')
```

**Comment by oberstet** [comment]
Oops. 

>  seems to only make a cosmetic change

No excuse, but the motivation is to improve our logging and user feedback experience. Which *is* good, and was (partially still is) one of the major user complaints. So I'd like to keep - in principle - representing peer strings that result in log messages which makes clear it's a pipe the peer is connected over.

Now, this doesn't address the issue of course;) Need to find a fix for that.

Importing from private Twisted: yeah. Probably Twisted has something in it's public API we can use? @hawkowl ?

The elephant in the room however is: why did we fail to catch that issue *before* doing a release?

As a matter of fact:

* none of the core devs is on Windows (any more)
* none of our own Crossbar.io deployments is on Windows
* our Travis CI tests a lot of variants .. but not on Windows
* Travis [doesn't support Windows ](https://github.com/travis-ci/travis-ci/issues/2104)

**Comment by meejah** [comment]
I could do something a little cheezy like:

```python
try:
    import ... PipeAddress
except:
    PipeAddress = None
```

**Comment by bb4242** [comment]
I believe this problem also affects crossbar on windows:

```
PS C:\Users\vagrant\crossbar> crossbar start --cbdir C:\Users\vagrant\.crossbar
2015-09-11T09:54:44-0700 [Controller   3952] WARNING: Running on Windows, but cannot install IOCP Twisted reactor (No mo
dule named win32api).
2015-09-11T09:54:44-0700 [Controller   3952] ←[33m←[1m     __  __  __  __  __  __      __     __←[0m
2015-09-11T09:54:44-0700 [Controller   3952] ←[33m←[1m    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \←[0m
2015-09-11T09:54:44-0700 [Controller   3952] ←[33m←[1m    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/←[0m
2015-09-11T09:54:44-0700 [Controller   3952] ←[33m←[1m                                        ←[0m
2015-09-11T09:54:44-0700 [Controller   3952]     Version: ←[33m←[1m0.11.0←[0m
2015-09-11T09:54:44-0700 [Controller   3952]
2015-09-11T09:54:44-0700 [Controller   3952] Starting from node directory C:\Users\vagrant\.crossbar
2015-09-11T09:54:44-0700 [Controller   3952] Traceback (most recent call last):
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\Scripts\crossbar-script.py", line 9, in <module>
2015-09-11T09:54:44-0700 [Controller   3952]     load_entry_point('crossbar==0.11.0', 'console_scripts', 'crossbar')()
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\crossbar\controller\cli.py", line 826
, in run
2015-09-11T09:54:44-0700 [Controller   3952]     options.func(options, reactor=reactor)
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\crossbar\controller\cli.py", line 515
, in run_command_start
2015-09-11T09:54:44-0700 [Controller   3952]     from crossbar.controller.node import Node
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\crossbar\controller\node.py", line 44
, in <module>
2015-09-11T09:54:44-0700 [Controller   3952]     from autobahn.twisted.wamp import ApplicationRunner
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\autobahn\twisted\wamp.py", line 40, i
n <module>
2015-09-11T09:54:44-0700 [Controller   3952]     from autobahn.twisted.websocket import WampWebSocketClientFactory
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\autobahn\twisted\websocket.py", line
42, in <module>
2015-09-11T09:54:44-0700 [Controller   3952]     from autobahn.twisted.util import peer2str
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\autobahn\twisted\util.py", line 31, i
n <module>
2015-09-11T09:54:44-0700 [Controller   3952]     from twisted.internet._posixstdio import PipeAddress
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\twisted\internet\_posixstdio.py", lin
e 16, in <module>
2015-09-11T09:54:44-0700 [Controller   3952]     from twisted.internet import process, error, interfaces
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\twisted\internet\process.py", line 11
9, in <module>
2015-09-11T09:54:44-0700 [Controller   3952]     brokenLinuxPipeBehavior = detectLinuxBrokenPipeBehavior()
2015-09-11T09:54:44-0700 [Controller   3952]   File "C:\Python27\lib\site-packages\twisted\internet\process.py", line 10
7, in detectLinuxBrokenPipeBehavior
2015-09-11T09:54:44-0700 [Controller   3952]     reads, writes, exes = select.select([w], [], [], 0)
2015-09-11T09:54:44-0700 [Controller   3952] select.error: (10038, 'An operation was attempted on something that is not
a socket')
```
Crossbar's `setup.py` contains `autobahn[twisted]>=0.10.7` as a dependency, but version 0.10.7 does not yet contain this fix.  Would it be possible to release autobahn 0.10.8 soon?  It would probably also be good to also update crossbar's dependency to be `autobahn[twisted]>=0.10.8` after the release is made.

Thanks!

**Comment by meejah** [comment]
FWIW, you can use pip to install AutobahnPython master in the meantime:

``pip install -e git+https://github.com/tavendo/AutobahnPython.git#egg=autobahn``

**Comment by bb4242** [comment]
Haha, yep, I just cloned AutobahnPython and did a `python setup.py install` manually.  But I didn't know you could do the same thing with pip - thanks for the tip!
